# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=10)),
                ('trackid', models.CharField(max_length=10)),
            ],
        ),
    ]
