# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQXM', '0002_auto_20190112_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('passwords', models.CharField(max_length=20)),
            ],
        ),
    ]
