# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQXM', '0007_shopcar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='age',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.AddField(
            model_name='details',
            name='discount',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='hh',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='img',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='img0',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='price2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='shopcar',
            table='JX_shopcar',
        ),
    ]
