# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JQXM', '0008_auto_20190118_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='img0',
        ),
    ]
